parameters:
    memory_data_dir: '%kernel.project_dir%/data/memory'
    memory_filename: 'user.json'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Memory\Core\Storage\StorageInterface:
        class: Memory\Core\Storage\FilesystemStorage
        arguments:
            $dataDir: '%memory_data_dir%'
            $filename: '%memory_filename%'
