parameters:
    log.level: '%env(LOG_LEVEL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            string $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/*'
        exclude:
            - '../src/Console/Command/*'

    App\Console\Command\:
        resource: '../src/Console/Command/*'
        tags: ['console.command']
